# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0002_remove_goal_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
