# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tm', '0003_goal_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tm.Goal')),
            ],
        ),
    ]
